const wordList = {
  easy: [
    "Angel",
    "Eyeball",
    "Pizza",
    "Angry",
    "Fireworks",
    "Pumpkin",
    "Baby",
    "Flower",
    "Rainbow",
    "Beard",
    "Flying saucer",
    "Recycle",
    "Bible",
    "Giraffe",
    "Sand castle",
    "Bikini",
    "Glasses",
    "Snowflake",
    "Book",
    "High heel",
    "Stairs",
    "Bucket",
    "Ice cream cone",
    "Starfish",
    "Bumble bee",
    "Igloo",
    "Strawberry",
    "Butterfly",
    "Lady bug",
    "Sun",
    "Camera",
    "Lamp",
    "Tire",
    "Cat",
    "Lion",
    "Toast",
    "Church",
    "Mailbox",
    "Toothbrush",
    "Crayon",
    "Night",
    "Toothpaste",
    "Dolphin",
    "Nose",
    "Truck",
    "Egg",
    "Olympics",
    "Volleyball",
    "Eiffel Tower",
    "Peanut",
    "Mind Your Manners"
  ],
  medium: [
    "Abraham Lincoln",
    "Brain",
    "Bubble bath",
    "Buckle",
    "Bus",
    "Car accident",
    "Castle",
    "Chain saw",
    "Circus tent",
    "Computer",
    "Crib",
    "Dragon",
    "Dumbbell",
    "Eel",
    "Ferris wheel",
    "Flag",
    "Junk mail",
    "Kiss",
    "Kitten",
    "Kiwi",
    "Lipstick",
    "Lobster",
    "Lollipop",
    "Magnet",
    "Megaphone",
    "Mermaid",
    "Minivan",
    "Mount Rushmore",
    "Music",
    "North pole",
    "Nurse",
    "Owl",
    "Pacifier",
    "Piano",
    "Pigtails",
    "Playground",
    "Pumpkin pie",
    "Raindrop",
    "Robot",
    "Sand castle",
    "Slipper",
    "Snowball",
    "Sprinkler",
    "Statue of Liberty",
    "Tadpole",
    "Teepee",
    "Telescope",
    "Train",
    "Tricycle",
    "Tutu",
    "Cold Water",
    "Bacon",
    "Hawaii",
    "Half Moon",
    "Harry Potter"
  ],
  hard: [
    "Attic",
    "Back seat",
    "Birthday",
    "Black hole",
    "Blizzard",
    "Burrito",
    "Captain",
    "Chandelier",
    "Crib",
    "Cruise ship",
    "Dance",
    "Deodorant",
    "Facebook",
    "Flat",
    "Frame",
    "Full moon",
    "Game",
    "Glue",
    "Highchair",
    "Hockey",
    "Hotel",
    "Jump rope",
    "Koala",
    "Leprechaun",
    "Light",
    "Mask",
    "Mechanic",
    "Mom",
    "Mr Potato Head",
    "Pantyhose",
    "Paper plate",
    "Photo",
    "Pilgram",
    "Pirate",
    "Pocket watch",
    "Rock band",
    "Sasquatch",
    "Scrambled eggs",
    "Seat belt",
    "Skip",
    "Solar eclipse",
    "Space",
    "Stethoscope",
    "Stork",
    "Sunburn",
    "Thread",
    "Tourist",
    "United States",
    "WIFI",
    "Zombie",
    "Hopscotch",
    "Candy Crush",
    "Where's Waldo",
    "Blue Jeans",
    "Humpty Dumpty",
    "Puss-in-Boots",
    "The Little Mermaid",
    "Teenage Mutant Ninja Turtles",
    "Strawberry Milkshake"
  ]
};

module.exports = wordList;
